"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'dummy-secret-key-for-dev-only')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'False').lower() in ('true', '1', 'yes')

ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',  # 跨域工具
    'judge',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# 配置主从数据库双引擎 (指向你真实的 Docker MySQL)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'geek_oj',                  # 👑 主库：负责写
        'USER': 'root',
        'PASSWORD': os.environ.get('MYSQL_ROOT_PASSWORD', 'root_password_123'),
        'HOST': os.environ.get('MYSQL_HOST', 'mysql_db'),
        'PORT': os.environ.get('MYSQL_PORT', '3306'),
        'OPTIONS': {
            'charset': 'utf8mb4',
        }
    },
    'replica': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'geek_oj',                  # 🛡️ 从库：负责读 (目前模拟指向同一个物理库)
        'USER': 'root',
        'PASSWORD': os.environ.get('MYSQL_ROOT_PASSWORD', 'root_password_123'),
        'HOST': os.environ.get('MYSQL_REPLICA_HOST', 'mysql_db'),
        'PORT': os.environ.get('MYSQL_REPLICA_PORT', '3306'),
        'OPTIONS': {
            'charset': 'utf8mb4',
        }
    }
}

# 挂载流量交警路由器
DATABASE_ROUTERS = ['judge.router.MasterSlaveRouter']



# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Cache: use Redis if available, else local memory (dev-safe)
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'oj-dashboard',
    }
}
# If Redis is reachable, prefer it for shared caching
_REDIS_HOST = os.environ.get('REDIS_HOST', 'redis_db')
_REDIS_PORT = os.environ.get('REDIS_PORT', '6379')
_REDIS_PASS = os.environ.get('REDIS_PASSWORD', 'redis_dev_pass')
try:
    from redis import Redis
    _r = Redis(host=_REDIS_HOST, port=int(_REDIS_PORT), password=_REDIS_PASS,
               socket_connect_timeout=1)
    _r.ping()
    _r.close()
    CACHES['default'] = {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': f'redis://:{_REDIS_PASS}@{_REDIS_HOST}:{_REDIS_PORT}/1',
    }
except Exception:
    pass  # fallback to LocMemCache

# CORS: read allowed origins from env, default to localhost for dev
CORS_ALLOWED_ORIGINS = os.environ.get(
    'CORS_ALLOWED_ORIGINS',
    'http://localhost:5173,http://127.0.0.1:5173'
).split(',')

# ============================================
# 🔒 Production safety: reject dummy defaults
# ============================================
if not DEBUG:
    _dummy_keys = ('dummy-secret-key-for-dev-only', 'dummy-jwt-key-for-dev-only',
                   'django-insecure', 'change-me')
    _secret = os.environ.get('DJANGO_SECRET_KEY', '')
    _jwt = os.environ.get('JWT_SECRET_KEY', '')
    if any(d in _secret for d in _dummy_keys) or any(d in _jwt for d in _dummy_keys):
        raise RuntimeError(
            "Production refused: DJANGO_SECRET_KEY and JWT_SECRET_KEY must be set "
            "to strong random values (not dummy/dev defaults)."
        )
    if os.environ.get('MYSQL_ROOT_PASSWORD', '') in ('root_password_123', '', 'change-me'):
        raise RuntimeError(
            "Production refused: MYSQL_ROOT_PASSWORD must be set to a strong password."
        )