# Generated by Django 6.0.5 on 2026-05-25 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='题目名称')),
                ('description', models.TextField(verbose_name='题目描述')),
                ('time_limit', models.IntegerField(default=1000, verbose_name='时间限制(ms)')),
                ('memory_limit', models.IntegerField(default=256, verbose_name='内存限制(MB)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(verbose_name='源代码')),
                ('language', models.CharField(default='python3', max_length=20, verbose_name='语言')),
                ('status', models.CharField(choices=[('PENDING', '等待评测'), ('JUDGING', '评测中'), ('AC', '答案正确 (Accepted)'), ('WA', '答案错误 (Wrong Answer)'), ('TLE', '运行超时 (Time Limit Exceeded)'), ('MLE', '内存超限 (Memory Limit Exceeded)'), ('CE', '编译错误 (Compile Error)')], default='PENDING', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.problem', verbose_name='题目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='提交者')),
            ],
        ),
    ]
