# Generated by Django 6.0.5 on 2026-06-14 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.TextField(help_text='测试输入数据')),
                ('expected_output', models.TextField(help_text='期望的正确输出数据')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='judge.problem')),
            ],
        ),
    ]
