# Generated by Django 6.0.5 on 2026-06-16 05:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0002_testcase'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='帖子标题')),
                ('content', models.TextField(verbose_name='帖子内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
            ],
            options={
                'verbose_name': '社区帖子',
                'verbose_name_plural': '社区帖子',
            },
        ),
        migrations.AlterField(
            model_name='problem',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='题目描述'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='提交时间'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('PENDING', '等待评测'), ('JUDGING', '评测中'), ('AC', '答案正确 (Accepted)'), ('WA', '答案错误 (Wrong Answer)'), ('TLE', '运行超时 (Time Limit Exceeded)'), ('MLE', '内存超限 (Memory Limit Exceeded)'), ('CE', '编译错误 (Compile Error)')], db_index=True, default='PENDING', max_length=20, verbose_name='状态'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['created_at'], name='judge_submi_created_24cdea_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['status', 'user'], name='judge_submi_status_950818_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['status'], name='judge_submi_status_72bad0_idx'),
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者'),
        ),
        migrations.AddField(
            model_name='post',
            name='problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='judge.problem', verbose_name='关联题目'),
        ),
    ]
